# Outputs of azuread_application resource

output "object_id" {
  description = "The object id of application. Can be used to assign roles to user."
  value       = azuread_application.main.object_id

}

output "client_id" {
  description = "The application id of AzureAD application created."
  value       = azuread_application.main.application_id
}

output "logo_url" {
  description = "CDN URL to the application's logo, as uploaded with the logo_image property."
  value       = azuread_application.main.logo_url
}

output "disabled_by_microsoft" {
  description = "Whether Microsoft has disabled the registered application. If the application is disabled, this will be a string indicating the status/reason, e.g. DisabledDueToViolationOfServicesAgreement."
  value       = azuread_application.main.disabled_by_microsoft
}

output "publisher_domain" {
  description = "The verified publisher domain for the application."
  value       = azuread_application.main.publisher_domain
}


# Outputs of azuread_service_principal resource

output "app_role_ids" {
  description = "A mapping of app role values to app role IDs, as published by the associated application, intended to be useful when referencing app roles in other resources in your configuration."
  value       = azuread_service_principal.main.app_role_ids
}


output "sp_object_id" {
  description = "The object Id of Service principal."
  value       = azuread_service_principal.main.object_id
}

output "oauth2_permission_scope_ids" {
  description = "A mapping of OAuth2.0 permission scope values to scope IDs."
  value       = azuread_service_principal.main.oauth2_permission_scope_ids
}

output "oauth2_permission_scopes" {
  description = " A list of OAuth 2.0 delegated permission scopes exposed by the associated application."
  value       = azuread_service_principal.main.oauth2_permission_scopes
}

output "app_roles" {
  description = "A list of app roles published by the associated application."
  value       = azuread_service_principal.main.app_roles
}

output "application_tenant_id" {
  description = "The tenant ID where the associated application is registered."
  value       = azuread_service_principal.main.application_tenant_id
}

output "display_name" {
  description = "The display name of the application associated with this service principal."
  value       = azuread_service_principal.main.display_name
}

output "homepage_url" {
  description = "Home page or landing page of the associated application."
  value       = azuread_service_principal.main.homepage_url
}

output "logout_url" {
  description = "The URL that will be used by Microsoft's authorization service to log out an user using OpenId Connect front-channel, back-channel or SAML logout protocols, taken from the associated application."
  value       = azuread_service_principal.main.logout_url
}

output "service_principal_names" {
  description = "A list of identifier URI(s), copied over from the associated application."
  value       = azuread_service_principal.main.service_principal_names
}

output "sign_in_audience" {
  description = "The Microsoft account types that are supported for the associated application. Possible values include AzureADMyOrg, AzureADMultipleOrgs, AzureADandPersonalMicrosoftAccount or PersonalMicrosoftAccount."
  value       = azuread_service_principal.main.sign_in_audience
}

output "type" {
  description = "Identifies whether the service principal represents an application or a managed identity."
  value       = azuread_service_principal.main.type
}



# Outputs of azuread_application_password resource

output "key_id" {
  description = "A UUID used to uniquely identify this password credential."
  value       = azuread_application_password.main.key_id
}

output "client_secret" {
  description = "The password for this application, which is generated by Azure Active Directory."
  value       = azuread_application_password.main.value
  sensitive   = true
}







